# generated by datamodel-codegen:
#   filename:  stagehand.v4.json

from typing import Any, Literal, NotRequired, Optional, TypeAlias, TypedDict, Union


class Action(TypedDict):
    selector: str
    description: str
    method: NotRequired[str]
    arguments: NotRequired[list[str]]


class ActResultData(TypedDict):
    success: bool
    message: str
    action_description: str
    actions: list[Action]


AnthropicModelName: TypeAlias = str


class BrowserbaseContext(TypedDict):
    id: str
    persist: NotRequired[bool]


class BrowserbaseFingerprintScreen(TypedDict):
    max_height: NotRequired[float]
    max_width: NotRequired[float]
    min_height: NotRequired[float]
    min_width: NotRequired[float]


class BrowserbaseFingerprint(TypedDict):
    browsers: NotRequired[list[Literal["chrome", "edge", "firefox", "safari"]]]
    devices: NotRequired[list[Literal["desktop", "mobile"]]]
    http_version: NotRequired[Literal["1", "2"]]
    locales: NotRequired[list[str]]
    operating_systems: NotRequired[list[Literal["android", "ios", "linux", "macos", "windows"]]]
    screen: NotRequired[BrowserbaseFingerprintScreen]


class BrowserbaseProxyGeolocation(TypedDict):
    country: str
    city: NotRequired[str]
    state: NotRequired[str]


class BrowserbaseProxyConfig(TypedDict):
    type: Literal["browserbase"]
    domain_pattern: NotRequired[str]
    geolocation: NotRequired[BrowserbaseProxyGeolocation]


BrowserbaseRegion: TypeAlias = Literal["us-west-2", "us-east-1", "eu-central-1", "ap-southeast-1"]


class BrowserSessionMetadata(TypedDict):
    session_id: str
    region: NotRequired[BrowserbaseRegion]


class BrowserbaseViewport(TypedDict):
    width: NotRequired[float]
    height: NotRequired[float]


class BrowserbaseBrowserSettings(TypedDict):
    advanced_stealth: NotRequired[bool]
    block_ads: NotRequired[bool]
    captcha_image_selector: NotRequired[str]
    captcha_input_selector: NotRequired[str]
    context: NotRequired[BrowserbaseContext]
    extension_id: NotRequired[str]
    fingerprint: NotRequired[BrowserbaseFingerprint]
    log_session: NotRequired[bool]
    os: NotRequired[Literal["windows", "mac", "linux", "mobile", "tablet"]]
    record_session: NotRequired[bool]
    solve_captchas: NotRequired[bool]
    verified: NotRequired[bool]
    viewport: NotRequired[BrowserbaseViewport]


CacheStatus: TypeAlias = Literal["HIT", "MISS", "DISABLED"]


class CacheTokenSavings(TypedDict):
    input_tokens: NotRequired[int]
    output_tokens: NotRequired[int]
    total_tokens: NotRequired[int]


class CacheMetadata(TypedDict):
    status: CacheStatus
    count: NotRequired[int]
    threshold: NotRequired[int]
    miss_reason: NotRequired[str]
    tokens_saved: NotRequired[CacheTokenSavings]


class Caching1(TypedDict):
    threshold: NotRequired[int]


Caching: TypeAlias = bool | Caching1


class CallbackBatchOptions(TypedDict):
    page_id: NotRequired[str]
    timeout: NotRequired[int]


CerebrasModelName: TypeAlias = str


class ClientModelReference(TypedDict):
    source: Literal["client"]


class ContextAddInitScriptParams(TypedDict):
    source: str


class ContextClipboardPasteParams(TypedDict):
    page_id: NotRequired[str]
    shortcut: NotRequired[Literal["ControlOrMeta+V", "Meta+V", "Control+V"]]


ContextClipboardReadTextResult: TypeAlias = str


class ContextClipboardTarget(TypedDict):
    page_id: NotRequired[str]


class ContextClipboardWriteTextParams(TypedDict):
    page_id: NotRequired[str]
    text: str


class ContextCookiesParams(TypedDict):
    urls: NotRequired[str | list[str]]


class ContextNewPageParams(TypedDict):
    url: NotRequired[str]


class ContextSetActivePageParams(TypedDict):
    page_id: str


class ContextSetExtraHTTPHeadersParams(TypedDict):
    headers: dict[str, str]


class ContextVoidResult(TypedDict):
    ok: Literal[True]


class Cookie(TypedDict):
    name: str
    value: str
    domain: str
    path: str
    expires: float
    http_only: bool
    secure: bool
    same_site: Literal["Strict", "Lax", "None"]


ContextCookiesResult: TypeAlias = list[Cookie]


class CookieParam(TypedDict):
    name: str
    value: str
    url: NotRequired[str]
    domain: NotRequired[str]
    path: NotRequired[str]
    expires: NotRequired[float]
    http_only: NotRequired[bool]
    secure: NotRequired[bool]
    same_site: NotRequired[Literal["Strict", "Lax", "None"]]


class ContextAddCookiesParams(TypedDict):
    cookies: list[CookieParam]


class CookieRegex(TypedDict):
    source: str
    flags: NotRequired[str]


CookieFilter: TypeAlias = str | CookieRegex


class ClearCookieOptions(TypedDict):
    name: NotRequired[CookieFilter]
    domain: NotRequired[CookieFilter]
    path: NotRequired[CookieFilter]


class ContextClearCookiesParams(TypedDict):
    options: NotRequired[ClearCookieOptions]


class DomainPolicy(TypedDict):
    allowed_domains: NotRequired[list[str]]
    blocked_domains: NotRequired[list[str]]


ContextGetDomainPolicyResult: TypeAlias = DomainPolicy | None


class ContextSetDomainPolicyParams(TypedDict):
    policy: DomainPolicy | None


class EmptyParams(TypedDict):
    pass


class ExternalProxyConfig(TypedDict):
    type: Literal["external"]
    server: str
    domain_pattern: NotRequired[str]
    username: NotRequired[str]
    password: NotRequired[str]


FieldSchema0: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema0"], dict[str, "FieldSchema0"]]]


FieldSchema1: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema1"], dict[str, "FieldSchema1"]]]


FieldSchema10: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema10"], dict[str, "FieldSchema10"]]]


FieldSchema11: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema11"], dict[str, "FieldSchema11"]]]


FieldSchema12: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema12"], dict[str, "FieldSchema12"]]]


FieldSchema13: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema13"], dict[str, "FieldSchema13"]]]


FieldSchema14: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema14"], dict[str, "FieldSchema14"]]]


FieldSchema2: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema2"], dict[str, "FieldSchema2"]]]


class CallbackBatchParams(TypedDict):
    callback_source: str
    input: NotRequired[FieldSchema2]
    options: CallbackBatchOptions


FieldSchema3: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema3"], dict[str, "FieldSchema3"]]]


class CallbackBatchResult(TypedDict):
    value: NotRequired[FieldSchema3]


FieldSchema4: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema4"], dict[str, "FieldSchema4"]]]


FieldSchema5: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema5"], dict[str, "FieldSchema5"]]]


FieldSchema6: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema6"], dict[str, "FieldSchema6"]]]


FieldSchema7: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema7"], dict[str, "FieldSchema7"]]]


FieldSchema8: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema8"], dict[str, "FieldSchema8"]]]


FieldSchema9: TypeAlias = Optional[Union[str, float, bool, list["FieldSchema9"], dict[str, "FieldSchema9"]]]


GoogleModelName: TypeAlias = str


GroqModelName: TypeAlias = str


class ImplementationInfo(TypedDict):
    name: str
    version: str


class InputFilePayload(TypedDict):
    name: str
    mime_type: NotRequired[str]
    data: str
    last_modified: NotRequired[int]


class JSONRPCErrorObject(TypedDict):
    code: int
    message: str
    data: NotRequired[FieldSchema14]


JSONRPCRequestId: TypeAlias = int


JSONRPCErrorResponseId: TypeAlias = JSONRPCRequestId | None


class LLMJsonSchemaResponseFormat(TypedDict):
    type: Literal["json_schema"]
    name: str
    description: NotRequired[str]
    schema: FieldSchema6


LLMRole: TypeAlias = Literal["user", "assistant"]


class LLMAnnotations(TypedDict):
    audience: NotRequired[list[LLMRole]]
    priority: NotRequired[float]
    last_modified: NotRequired[str]


class LLMImageContent(TypedDict):
    type: Literal["image"]
    data: str
    mime_type: str
    annotations: NotRequired[LLMAnnotations]


class LLMTextContent(TypedDict):
    type: Literal["text"]
    text: str
    annotations: NotRequired[LLMAnnotations]


class LLMTextResponseFormat(TypedDict):
    type: Literal["text"]


class LLMToolAnnotations(TypedDict):
    title: NotRequired[str]
    read_only_hint: NotRequired[bool]
    destructive_hint: NotRequired[bool]
    idempotent_hint: NotRequired[bool]
    open_world_hint: NotRequired[bool]


class LLMToolChoice(TypedDict):
    mode: NotRequired[Literal["auto", "required", "none"]]


class LLMToolExecution(TypedDict):
    task_support: NotRequired[Literal["forbidden", "optional", "required"]]


class LLMToolIcon(TypedDict):
    src: str
    mime_type: NotRequired[str]
    sizes: NotRequired[list[str]]
    theme: NotRequired[Literal["light", "dark"]]


LLMToolJson = TypedDict(
    "LLMToolJson",
    {
        "$schema": NotRequired[str],
        "type": Literal["object"],
        "properties": NotRequired[dict[str, dict[str, FieldSchema7]]],
        "required": NotRequired[list[str]],
    },
)


class LLMClientTool(TypedDict):
    name: str
    title: NotRequired[str]
    icons: NotRequired[list[LLMToolIcon]]
    description: NotRequired[str]
    input_schema: LLMToolJson
    execution: NotRequired[LLMToolExecution]
    output_schema: NotRequired[LLMToolJson]
    annotations: NotRequired[LLMToolAnnotations]


LLMToolResultContentBlock: TypeAlias = LLMTextContent | LLMImageContent


class LLMToolResultContent(TypedDict):
    type: Literal["tool_result"]
    tool_use_id: str
    content: list[LLMToolResultContentBlock]
    structured_content: NotRequired[dict[str, FieldSchema5]]
    is_error: NotRequired[bool]


class LLMToolUseContent(TypedDict):
    type: Literal["tool_use"]
    id: str
    name: str
    input: dict[str, FieldSchema4]


LLMMessageContentBlock: TypeAlias = LLMTextContent | LLMImageContent | LLMToolUseContent | LLMToolResultContent


class LLMMessage(TypedDict):
    role: LLMRole
    content: LLMMessageContentBlock | list[LLMMessageContentBlock]


class LLMMessageGenerateParams(TypedDict):
    messages: list[LLMMessage]
    system_prompt: NotRequired[str]
    temperature: NotRequired[float]
    stop_sequences: NotRequired[list[str]]
    tools: NotRequired[list[LLMClientTool]]
    tool_choice: NotRequired[LLMToolChoice]
    response_format: NotRequired[LLMTextResponseFormat]


class LLMStructuredGenerateParams(TypedDict):
    messages: list[LLMMessage]
    system_prompt: NotRequired[str]
    temperature: NotRequired[float]
    stop_sequences: NotRequired[list[str]]
    response_format: LLMJsonSchemaResponseFormat


LLMGenerateParams: TypeAlias = LLMStructuredGenerateParams | LLMMessageGenerateParams


class LLMUsage(TypedDict):
    input_tokens: int
    output_tokens: int
    total_tokens: int
    reasoning_tokens: NotRequired[int]
    cached_input_tokens: NotRequired[int]


class LLMMessageGenerateResult(TypedDict):
    role: LLMRole
    content: LLMMessageContentBlock | list[LLMMessageContentBlock]
    stop_reason: NotRequired[str]
    usage: NotRequired[LLMUsage]
    output_format: Literal["text"]


class LLMStructuredGenerateResult(TypedDict):
    role: LLMRole
    content: LLMMessageContentBlock | list[LLMMessageContentBlock]
    stop_reason: NotRequired[str]
    usage: NotRequired[LLMUsage]
    output_format: Literal["json_schema"]
    structured_content: FieldSchema8


LLMGenerateResult: TypeAlias = LLMMessageGenerateResult | LLMStructuredGenerateResult


LoadState: TypeAlias = Literal["load", "domcontentloaded", "networkidle"]


class Locator(TypedDict):
    selector: str
    nth: NotRequired[int]


class LocatorCentroidResult(TypedDict):
    x: float
    y: float


class LocatorClickResult(TypedDict):
    clicked: Literal[True]


LocatorCountResult: TypeAlias = int


class LocatorDescriptor(TypedDict):
    page_id: str
    selector: str
    nth: NotRequired[int]


class LocatorFillParams(TypedDict):
    page_id: str
    selector: str
    nth: NotRequired[int]
    value: str


class LocatorFillResult(TypedDict):
    filled: Literal[True]


class LocatorHighlightResult(TypedDict):
    highlighted: Literal[True]


class LocatorHoverResult(TypedDict):
    hovered: Literal[True]


LocatorInnerHtmlResult: TypeAlias = str


LocatorInnerTextResult: TypeAlias = str


LocatorInputValueResult: TypeAlias = str


LocatorIsCheckedResult: TypeAlias = bool


LocatorIsVisibleResult: TypeAlias = bool


class LocatorScrollToParams(TypedDict):
    page_id: str
    selector: str
    nth: NotRequired[int]
    percent: float | str


class LocatorScrollToResult(TypedDict):
    scrolled: Literal[True]


class LocatorSelectOptionParams(TypedDict):
    page_id: str
    selector: str
    nth: NotRequired[int]
    values: str | list[str]


LocatorSelectOptionResult: TypeAlias = list[str]


class LocatorSendClickEventOptions(TypedDict):
    bubbles: NotRequired[bool]
    cancelable: NotRequired[bool]
    composed: NotRequired[bool]
    detail: NotRequired[float]


class LocatorSendClickEventParams(TypedDict):
    page_id: str
    selector: str
    nth: NotRequired[int]
    options: NotRequired[LocatorSendClickEventOptions]


class LocatorSendClickEventResult(TypedDict):
    clicked: Literal[True]


class LocatorSetInputFilesParams(TypedDict):
    page_id: str
    selector: str
    nth: NotRequired[int]
    files: list[InputFilePayload]


class LocatorSetInputFilesResult(TypedDict):
    set: Literal[True]


LocatorTextContentResult: TypeAlias = str


class LocatorTypeOptions(TypedDict):
    delay: NotRequired[float]


class LocatorTypeParams(TypedDict):
    page_id: str
    selector: str
    nth: NotRequired[int]
    text: str
    options: NotRequired[LocatorTypeOptions]


class LocatorTypeResult(TypedDict):
    typed: Literal[True]


MouseButton: TypeAlias = Literal["left", "right", "middle"]


class LocatorClickOptions(TypedDict):
    button: NotRequired[MouseButton]
    click_count: NotRequired[int]


class LocatorClickParams(TypedDict):
    page_id: str
    selector: str
    nth: NotRequired[int]
    options: NotRequired[LocatorClickOptions]


class NavigationFinishedError(TypedDict):
    message: str


class NavigationHeader(TypedDict):
    name: str
    value: str


class NavigationResponseDescriptor(TypedDict):
    response_id: str
    url: str
    status: int
    status_text: str
    headers: dict[str, str]
    from_service_worker: bool


class NavigationSecurityDetails(TypedDict):
    issuer: str
    protocol: str
    subject_name: str
    valid_from: float
    valid_to: float


class NavigationServerAddr(TypedDict):
    ip_address: str
    port: int


OpenAIModelName: TypeAlias = str


ModelName: TypeAlias = OpenAIModelName | AnthropicModelName | GoogleModelName | GroqModelName | CerebrasModelName


class ModelConfig(TypedDict):
    api_key: NotRequired[str]
    headers: NotRequired[dict[str, str]]
    model_name: ModelName


class ExtractOptions(TypedDict):
    model: NotRequired[ModelConfig]
    timeout: NotRequired[float]
    locator: NotRequired[Locator]
    ignore_locators: NotRequired[list[Locator]]
    screenshot: NotRequired[bool]
    cache: NotRequired[Caching]


class PageAddInitScriptParams(TypedDict):
    page_id: str
    source: str


PageCDPEventParams: TypeAlias = dict[str, FieldSchema12]


class PageCDPEvent(TypedDict):
    page_id: str
    method: Literal["Runtime.consoleAPICalled"]
    params: PageCDPEventParams
    session_id: str
    target_id: str


class PageCDPEventNotification(TypedDict):
    subscription_id: str
    event: PageCDPEvent


class PageClickOptions(TypedDict):
    button: NotRequired[MouseButton]
    click_count: NotRequired[int]


class PageClickParams(TypedDict):
    page_id: str
    x: float
    y: float
    options: NotRequired[PageClickOptions]


class PageCloseResult(TypedDict):
    closed: Literal[True]


class PageDragAndDropRoutePoint(TypedDict):
    x: float
    y: float


class PageDragAndDropOptions(TypedDict):
    button: NotRequired[MouseButton]
    steps: NotRequired[int]
    delay: NotRequired[float]
    route: NotRequired[list[PageDragAndDropRoutePoint]]


class PageDragAndDropParams(TypedDict):
    page_id: str
    from_x: float
    from_y: float
    to_x: float
    to_y: float
    options: NotRequired[PageDragAndDropOptions]


class PageEvaluateParams(TypedDict):
    page_id: str
    expression: str


class PageEvaluateResult(TypedDict):
    value: FieldSchema9


PageEventName: TypeAlias = Literal["console"]


class PageHoverParams(TypedDict):
    page_id: str
    x: float
    y: float


class PageIdParams(TypedDict):
    page_id: str


class PageKeyPressOptions(TypedDict):
    delay: NotRequired[float]


class PageKeyPressParams(TypedDict):
    page_id: str
    key: str
    options: NotRequired[PageKeyPressOptions]


class PageNavigationOptions(TypedDict):
    wait_until: NotRequired[LoadState]
    timeout: NotRequired[int]


class PageGoBackParams(TypedDict):
    page_id: str
    options: NotRequired[PageNavigationOptions]


class PageGoForwardParams(TypedDict):
    page_id: str
    options: NotRequired[PageNavigationOptions]


class PageGotoParams(TypedDict):
    page_id: str
    url: str
    options: NotRequired[PageNavigationOptions]


class PageOffParams(TypedDict):
    subscription_id: str


class PageOnParams(TypedDict):
    page_id: str
    subscription_id: str
    event: PageEventName


class PageRef(TypedDict):
    page_id: str
    url: NotRequired[str]
    title: NotRequired[str]


ContextActivePageResult: TypeAlias = PageRef | None


ContextPagesResult: TypeAlias = list[PageRef]


class PageNavigationResult(TypedDict):
    page: PageRef
    response: NavigationResponseDescriptor | None


class PageReloadOptions(TypedDict):
    wait_until: NotRequired[LoadState]
    timeout: NotRequired[int]
    ignore_cache: NotRequired[bool]


class PageReloadParams(TypedDict):
    page_id: str
    options: NotRequired[PageReloadOptions]


class PageScreenshotClip(TypedDict):
    x: float
    y: float
    width: float
    height: float


class PageScreenshotOptions(TypedDict):
    animations: NotRequired[Literal["disabled", "allow"]]
    caret: NotRequired[Literal["hide", "initial"]]
    clip: NotRequired[PageScreenshotClip]
    full_page: NotRequired[bool]
    mask: NotRequired[list[LocatorDescriptor]]
    mask_color: NotRequired[str]
    omit_background: NotRequired[bool]
    quality: NotRequired[int]
    scale: NotRequired[Literal["css", "device"]]
    style: NotRequired[str]
    timeout: NotRequired[float]
    type: NotRequired[Literal["png", "jpeg"]]


class PageScreenshotParams(TypedDict):
    page_id: str
    options: NotRequired[PageScreenshotOptions]


class PageScreenshotResult(TypedDict):
    data: str


class PageScrollParams(TypedDict):
    page_id: str
    x: float
    y: float
    delta_x: float
    delta_y: float


class PageSetExtraHTTPHeadersParams(TypedDict):
    page_id: str
    headers: dict[str, str]


class PageSetViewportSizeOptions(TypedDict):
    device_scale_factor: NotRequired[float]


class PageSetViewportSizeParams(TypedDict):
    page_id: str
    width: int
    height: int
    options: NotRequired[PageSetViewportSizeOptions]


class PageSnapshotOptions(TypedDict):
    include_iframes: NotRequired[bool]


class PageSnapshotParams(TypedDict):
    page_id: str
    options: NotRequired[PageSnapshotOptions]


PageTitleResult: TypeAlias = str


class PageTypeOptions(TypedDict):
    delay: NotRequired[float]
    with_mistakes: NotRequired[bool]


class PageTypeParams(TypedDict):
    page_id: str
    text: str
    options: NotRequired[PageTypeOptions]


PageUrlResult: TypeAlias = str


class PageVoidResult(TypedDict):
    ok: Literal[True]


class PageWaitForLoadStateParams(TypedDict):
    page_id: str
    state: LoadState
    timeout: NotRequired[int]


class PageWaitForSelectorOptions(TypedDict):
    state: NotRequired[Literal["attached", "detached", "visible", "hidden"]]
    timeout: NotRequired[int]
    pierce_shadow: NotRequired[bool]


class PageWaitForSelectorParams(TypedDict):
    page_id: str
    selector: str
    options: NotRequired[PageWaitForSelectorOptions]


class PageWaitForSelectorResult(TypedDict):
    matched: bool


class PageWaitForTimeoutParams(TypedDict):
    page_id: str
    ms: int


class PageWebMCPCancelInvocationParams(TypedDict):
    page_id: str
    invocation_id: str


ProxyConfig: TypeAlias = BrowserbaseProxyConfig | ExternalProxyConfig


class BrowserbaseSessionCreateParams(TypedDict):
    browser_settings: NotRequired[BrowserbaseBrowserSettings]
    extension_id: NotRequired[str]
    keep_alive: NotRequired[bool]
    proxies: NotRequired[bool | list[ProxyConfig]]
    region: NotRequired[BrowserbaseRegion]
    timeout: NotRequired[float]
    user_metadata: NotRequired[dict[str, Any]]


class ResponseAllHeadersResult(TypedDict):
    headers: dict[str, str]


class ResponseBodyResult(TypedDict):
    body: str
    base64_encoded: Literal[True]


class ResponseFinishedResult(TypedDict):
    error: NavigationFinishedError | None


class ResponseHeadersArrayResult(TypedDict):
    headers: list[NavigationHeader]


class ResponseIdParams(TypedDict):
    response_id: str


class ResponseSecurityDetailsResult(TypedDict):
    value: NavigationSecurityDetails | None


class ResponseServerAddrResult(TypedDict):
    value: NavigationServerAddr | None


class RgbaColor(TypedDict):
    r: float
    g: float
    b: float
    a: NotRequired[float]


class LocatorHighlightOptions(TypedDict):
    duration_ms: NotRequired[int]
    border_color: NotRequired[RgbaColor]
    content_color: NotRequired[RgbaColor]


class LocatorHighlightParams(TypedDict):
    page_id: str
    selector: str
    nth: NotRequired[int]
    options: NotRequired[LocatorHighlightOptions]


class SnapshotResult(TypedDict):
    formatted_tree: str
    xpath_map: dict[str, str]
    url_map: dict[str, str]


class StagehandCloseResult(TypedDict):
    closed: Literal[True]


class StagehandExtractParams(TypedDict):
    page_id: str
    instruction: str
    schema: NotRequired[FieldSchema0]
    options: NotRequired[ExtractOptions]


class StagehandInitResult(TypedDict):
    initialized: Literal[True]
    pages: list[PageRef]


StagehandLogData: TypeAlias = dict[str, FieldSchema11]


StagehandLogLevel: TypeAlias = Literal["debug", "info", "warn", "error"]


class StagehandLog(TypedDict):
    level: StagehandLogLevel
    message: str
    data: StagehandLogData


class StagehandMetrics(TypedDict):
    act_prompt_tokens: float
    act_completion_tokens: float
    act_reasoning_tokens: float
    act_cached_input_tokens: float
    act_inference_time_ms: float
    extract_prompt_tokens: float
    extract_completion_tokens: float
    extract_reasoning_tokens: float
    extract_cached_input_tokens: float
    extract_inference_time_ms: float
    observe_prompt_tokens: float
    observe_completion_tokens: float
    observe_reasoning_tokens: float
    observe_cached_input_tokens: float
    observe_inference_time_ms: float
    total_prompt_tokens: float
    total_completion_tokens: float
    total_reasoning_tokens: float
    total_cached_input_tokens: float
    total_inference_time_ms: float


class StagehandResultUsage(TypedDict):
    input_tokens: NotRequired[int]
    output_tokens: NotRequired[int]
    reasoning_tokens: NotRequired[int]
    cached_input_tokens: NotRequired[int]
    inference_time_ms: NotRequired[int]


class StagehandResultMetadata(TypedDict):
    action_id: NotRequired[str]
    cache: CacheMetadata
    usage: StagehandResultUsage


class ActResult(TypedDict):
    data: ActResultData
    metadata: StagehandResultMetadata


class ExtractResult(TypedDict):
    data: FieldSchema1
    metadata: StagehandResultMetadata


class ObserveResult(TypedDict):
    data: list[Action]
    metadata: StagehandResultMetadata


class TelemetryTraces(TypedDict):
    endpoint: str
    headers: NotRequired[dict[str, str]]


class TelemetryConfig(TypedDict):
    traces: TelemetryTraces


class StagehandInitParams(TypedDict):
    protocol_version: str
    client_info: ImplementationInfo
    browser_cdp_url: NotRequired[str]
    api_key: NotRequired[str]
    api_url: NotRequired[str]
    browser: NotRequired[BrowserSessionMetadata]
    model: NotRequired[ModelConfig | ClientModelReference]
    telemetry: NotRequired[TelemetryConfig]
    log_level: NotRequired[Literal["off", "error", "warn", "info", "debug"]]
    system_prompt: NotRequired[str]
    self_heal: NotRequired[bool]
    dom_settle_timeout_ms: NotRequired[int]
    cache: NotRequired[Caching]


VariablePrimitive: TypeAlias = str | float | bool


class DescribedVariableValue(TypedDict):
    value: VariablePrimitive
    description: NotRequired[str]


VariableValue: TypeAlias = VariablePrimitive | DescribedVariableValue


Variables: TypeAlias = dict[str, VariableValue]


class ActOptions(TypedDict):
    model: NotRequired[ModelConfig]
    variables: NotRequired[Variables]
    timeout: NotRequired[float]
    locator: NotRequired[Locator]
    ignore_locators: NotRequired[list[Locator]]
    cache: NotRequired[Caching]


class ObserveOptions(TypedDict):
    model: NotRequired[ModelConfig]
    variables: NotRequired[Variables]
    timeout: NotRequired[float]
    locator: NotRequired[Locator]
    ignore_locators: NotRequired[list[Locator]]
    cache: NotRequired[Caching]


class StagehandActParams(TypedDict):
    page_id: str
    instruction: str | Action
    options: NotRequired[ActOptions]


class StagehandObserveParams(TypedDict):
    page_id: str
    instruction: NotRequired[str]
    options: NotRequired[ObserveOptions]


class WebMCPAnnotation(TypedDict):
    read_only: NotRequired[bool]
    untrusted_content: NotRequired[bool]
    autosubmit: NotRequired[bool]


WebMCPInvocationStatus: TypeAlias = Literal["Completed", "Canceled", "Error"]


WebMCPJsonValue: TypeAlias = FieldSchema10


class PageWebMCPInvokeToolParams(TypedDict):
    page_id: str
    frame_id: str
    tool_name: str
    input: NotRequired[dict[str, WebMCPJsonValue]]


class WebMCPInvocationDescriptor(TypedDict):
    invocation_id: str
    tool_name: str
    frame_id: str
    input: dict[str, WebMCPJsonValue]


WebMCPRemoteObject: TypeAlias = dict[str, WebMCPJsonValue]


class WebMCPResultOptions(TypedDict):
    timeout: NotRequired[float]


class PageWebMCPInvocationResultParams(TypedDict):
    page_id: str
    invocation_id: str
    options: NotRequired[WebMCPResultOptions]


class WebMCPToolDescriptor(TypedDict):
    name: str
    description: str
    input_schema: NotRequired[dict[str, WebMCPJsonValue]]
    annotations: NotRequired[WebMCPAnnotation]
    frame_id: str
    backend_node_id: NotRequired[int]


class PageWebMCPToolsResult(TypedDict):
    tools: list[WebMCPToolDescriptor]


class WebMCPToolResponse(TypedDict):
    invocation_id: str
    status: WebMCPInvocationStatus
    output: NotRequired[WebMCPJsonValue]
    error_text: NotRequired[str]
    exception: NotRequired[WebMCPRemoteObject]


class WebMCPToolsOptions(TypedDict):
    timeout: NotRequired[float]


class PageWebMCPToolsParams(TypedDict):
    page_id: str
    options: NotRequired[WebMCPToolsOptions]
