# generated by datamodel-codegen:
#   filename:  stagehand.v4.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal, Optional, Union

from pydantic import (
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
)
from stagehand._validation import (
    PageScreenshotOptionsValidation,
    TelemetryConfigValidation,
    WireModel,
    WireUrl,
)


class ActOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    model: Optional[ModelConfig] = None
    """Complete model configuration for this call; when omitted, the initialized Stagehand model is used, or Browserbase selects one automatically when no initialized model exists"""
    variables: Annotated[
        Optional[Variables],
        Field(
            examples=[{"username": "john_doe", "password": {"value": "secret123", "description": "The login password"}}]
        ),
    ] = None
    """
    Variables to substitute in the action instruction. Accepts flat primitives or { value, description? } objects.

    Example: {'username': 'john_doe', 'password': {'value': 'secret123', 'description': 'The login password'}}
    """
    timeout: Annotated[Optional[StrictFloat], Field(examples=[30000])] = None
    """
    Timeout in ms for the action

    Example: 30000
    """
    locator: Optional[Locator] = None
    """Serializable element locator for the action target"""
    ignore_locators: Annotated[
        Optional[list[Locator]],
        Field(
            examples=[[{"selector": "nav"}, {"selector": ".cookie-banner"}, {"selector": "#sidebar-ads"}]]
        ),
    ] = None
    """
    Locators for elements and subtrees that should be excluded from action planning

    Example: [{'selector': 'nav'}, {'selector': '.cookie-banner'}, {'selector': '#sidebar-ads'}]
    """
    cache: Optional[Caching] = None
    """Override the instance-level cache setting for this request"""


class ActResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    data: ActResultData
    metadata: StagehandResultMetadata


class ActResultData(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    success: Annotated[StrictBool, Field(examples=[True])]
    """
    Whether the action completed successfully

    Example: True
    """
    message: Annotated[
        StrictStr, Field(examples=["Successfully clicked the login button"])
    ]
    """
    Human-readable result message

    Example: 'Successfully clicked the login button'
    """
    action_description: Annotated[
        StrictStr, Field(examples=["Clicked button with text 'Login'"])
    ]
    """
    Description of the action that was performed

    Example: "Clicked button with text 'Login'"
    """
    actions: list[Action]
    """List of actions that were executed"""


class Action(WireModel):
    """Action object returned by observe and used by act"""

    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    selector: Annotated[StrictStr, Field(examples=["[data-testid='submit-button']"])]
    """
    CSS selector or XPath for the element

    Example: "[data-testid='submit-button']"
    """
    description: Annotated[StrictStr, Field(examples=["Click the submit button"])]
    """
    Human-readable description of the action

    Example: 'Click the submit button'
    """
    method: Annotated[Optional[StrictStr], Field(examples=["click"])] = None
    """
    The method to execute (click, fill, etc.)

    Example: 'click'
    """
    arguments: Annotated[Optional[list[StrictStr]], Field(examples=[["Hello World"]])] = (
        None
    )
    """
    Arguments to pass to the method

    Example: ['Hello World']
    """


class Animations(StrEnum):
    disabled = "disabled"
    allow = "allow"


class AnthropicModelName(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^anthropic\\/(claude-3-haiku-20240307|claude-haiku-4-5-20251001|claude-haiku-4-5|claude-opus-4-0|claude-opus-4-20250514|claude-opus-4-1-20250805|claude-opus-4-1|claude-opus-4-5|claude-opus-4-5-20251101|claude-sonnet-4-0|claude-sonnet-4-20250514|claude-sonnet-4-5-20250929|claude-sonnet-4-5|claude-sonnet-4-6|claude-opus-4-6|claude-opus-4-7|claude-opus-4-8|claude-fable-5|claude-sonnet-5)$"
        ),
    ]


class Browser(StrEnum):
    chrome = "chrome"
    edge = "edge"
    firefox = "firefox"
    safari = "safari"


class BrowserSessionMetadata(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    session_id: Annotated[StrictStr, Field(min_length=1)]
    region: Optional[BrowserbaseRegion] = None


class BrowserbaseBrowserSettings(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    advanced_stealth: Optional[StrictBool] = None
    block_ads: Optional[StrictBool] = None
    captcha_image_selector: Optional[StrictStr] = None
    captcha_input_selector: Optional[StrictStr] = None
    context: Optional[BrowserbaseContext] = None
    extension_id: Optional[StrictStr] = None
    fingerprint: Optional[BrowserbaseFingerprint] = None
    log_session: Optional[StrictBool] = None
    os: Optional[Os] = None
    record_session: Optional[StrictBool] = None
    solve_captchas: Optional[StrictBool] = None
    verified: Optional[StrictBool] = None
    viewport: Optional[BrowserbaseViewport] = None


class BrowserbaseContext(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    id: StrictStr
    persist: Optional[StrictBool] = None


class BrowserbaseFingerprint(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    browsers: Optional[list[Browser]] = None
    devices: Optional[list[Device]] = None
    http_version: Optional[HttpVersion] = None
    locales: Optional[list[StrictStr]] = None
    operating_systems: Optional[list[OperatingSystem]] = None
    screen: Optional[BrowserbaseFingerprintScreen] = None


class BrowserbaseFingerprintScreen(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    max_height: Optional[StrictFloat] = None
    max_width: Optional[StrictFloat] = None
    min_height: Optional[StrictFloat] = None
    min_width: Optional[StrictFloat] = None


class BrowserbaseProxyConfig(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    type: Literal["browserbase"]
    domain_pattern: Optional[StrictStr] = None
    geolocation: Optional[BrowserbaseProxyGeolocation] = None


class BrowserbaseProxyGeolocation(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    country: StrictStr
    city: Optional[StrictStr] = None
    state: Optional[StrictStr] = None


class BrowserbaseRegion(StrEnum):
    us_west_2 = "us-west-2"
    us_east_1 = "us-east-1"
    eu_central_1 = "eu-central-1"
    ap_southeast_1 = "ap-southeast-1"


class BrowserbaseSessionCreateParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    browser_settings: Optional[BrowserbaseBrowserSettings] = None
    extension_id: Optional[StrictStr] = None
    keep_alive: Optional[StrictBool] = None
    proxies: Optional[Union[StrictBool, list[ProxyConfig]]] = None
    region: Optional[BrowserbaseRegion] = None
    timeout: Optional[StrictFloat] = None
    user_metadata: Optional[dict[StrictStr, Any]] = None


class BrowserbaseViewport(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    width: Optional[StrictFloat] = None
    height: Optional[StrictFloat] = None


class CacheMetadata(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    status: CacheStatus
    """Whether server-side caching served this result, computed it, or was not consulted"""
    count: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    """Times this cache key has been seen, including this request; compare with threshold to see how close the key is to being served"""
    threshold: Annotated[Optional[StrictInt], Field(gt=0, le=9007199254740991)] = None
    """Hit-count threshold in effect for this key"""
    miss_reason: Optional[StrictStr] = None
    """Why the cache did not serve this request; misses only. Reported by the server: "not_found", "threshold", "empty_array", "timeout", "error", "bypass", "screenshot", "not_enabled", "no_cache_key". Reported locally: "read_failed" (the cache request itself failed) and "replay_failed" (a cached value was found but could not be applied)"""
    tokens_saved: Optional[CacheTokenSavings] = None
    """LLM tokens avoided by serving this request from cache; hits only"""


class CacheStatus(StrEnum):
    hit = "HIT"
    miss = "MISS"
    disabled = "DISABLED"


class CacheTokenSavings(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    input_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)] = 0
    output_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)] = 0
    total_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)] = 0


class Caching1(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    threshold: Annotated[Optional[StrictInt], Field(gt=0, le=9007199254740991)] = None


class Caching(RootModel[Union[StrictBool, Caching1]]):
    root: Union[StrictBool, Caching1]


class CallbackBatchOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: Annotated[Optional[StrictStr], Field(min_length=1)] = None
    timeout: Annotated[StrictInt, Field(gt=0, le=2147473647)] = 30000


class CallbackBatchParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    callback_source: Annotated[StrictStr, Field(min_length=1)]
    input: Optional[FieldSchema2] = None
    options: CallbackBatchOptions


class CallbackBatchResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    value: Optional[FieldSchema3] = None


class Caret(StrEnum):
    hide = "hide"
    initial = "initial"


class CerebrasModelName(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^cerebras\\/(llama3\\.1-8b|gpt-oss-120b|qwen-3-235b-a22b-instruct-2507|qwen-3-235b-a22b-thinking-2507|zai-glm-4\\.6|zai-glm-4\\.7)$"
        ),
    ]


class ClearCookieOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: Optional[CookieFilter] = None
    domain: Optional[CookieFilter] = None
    path: Optional[CookieFilter] = None


class ClientModelReference(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    source: Literal["client"]


class ContextAddCookiesParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    cookies: list[CookieParam]


class ContextAddInitScriptParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    source: StrictStr


class ContextClearCookiesParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    options: Optional[ClearCookieOptions] = None


class ContextClipboardPasteParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: Optional[StrictStr] = None
    shortcut: Optional[Shortcut] = None


class ContextClipboardReadTextResult(RootModel[StrictStr]):
    root: StrictStr


class ContextClipboardTarget(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: Optional[StrictStr] = None


class ContextClipboardWriteTextParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: Optional[StrictStr] = None
    text: StrictStr


class ContextCookiesParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    urls: Optional[Union[StrictStr, list[StrictStr]]] = None


class ContextNewPageParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    url: Annotated[Optional[StrictStr], Field(min_length=1)] = None


class ContextSetActivePageParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr


class ContextSetDomainPolicyParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    policy: Optional[DomainPolicy]


class ContextSetExtraHTTPHeadersParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    headers: dict[StrictStr, StrictStr]


class ContextVoidResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    ok: Literal[True]


class Cookie(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: StrictStr
    value: StrictStr
    domain: StrictStr
    path: StrictStr
    expires: StrictFloat
    http_only: StrictBool
    secure: StrictBool
    same_site: SameSite


class ContextCookiesResult(RootModel[list[Cookie]]):
    root: list[Cookie]


class CookieParam(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: StrictStr
    value: StrictStr
    url: Optional[StrictStr] = None
    domain: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    expires: Optional[StrictFloat] = None
    http_only: Optional[StrictBool] = None
    secure: Optional[StrictBool] = None
    same_site: Optional[SameSite] = None


class CookieRegex(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    source: StrictStr
    flags: Annotated[Optional[StrictStr], Field(pattern="^[dgimsuvy]*$")] = None


class CookieFilter(RootModel[Union[StrictStr, CookieRegex]]):
    root: Union[StrictStr, CookieRegex]


class DescribedVariableValue(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    value: VariablePrimitive
    description: Optional[StrictStr] = None


class Device(StrEnum):
    desktop = "desktop"
    mobile = "mobile"


class DomainPolicy(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    allowed_domains: Optional[list[StrictStr]] = None
    blocked_domains: Optional[list[StrictStr]] = None


class ContextGetDomainPolicyResult(RootModel[Optional[DomainPolicy]]):
    root: Optional[DomainPolicy]


class EmptyParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )


class ExternalProxyConfig(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    type: Literal["external"]
    server: StrictStr
    domain_pattern: Optional[StrictStr] = None
    username: Optional[StrictStr] = None
    password: Optional[StrictStr] = None


class ExtractOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    model: Optional[ModelConfig] = None
    """Complete model configuration for this call; when omitted, the initialized Stagehand model is used, or Browserbase selects one automatically when no initialized model exists"""
    timeout: Annotated[Optional[StrictFloat], Field(examples=[30000])] = None
    """
    Timeout in ms for the extraction

    Example: 30000
    """
    locator: Optional[Locator] = None
    """Locator that scopes extraction to a specific element"""
    ignore_locators: Annotated[
        Optional[list[Locator]],
        Field(
            examples=[[{"selector": "nav"}, {"selector": ".cookie-banner"}, {"selector": "#sidebar-ads"}]]
        ),
    ] = None
    """
    Locators for elements and subtrees that should be excluded from extraction

    Example: [{'selector': 'nav'}, {'selector': '.cookie-banner'}, {'selector': '#sidebar-ads'}]
    """
    screenshot: Annotated[Optional[StrictBool], Field(examples=[False])] = None
    """
    When true, include a screenshot of the current viewport in the extraction LLM call. Defaults to false.

    Example: False
    """
    cache: Optional[Caching] = None
    """Override the instance-level cache setting for this request"""


class ExtractResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    data: Optional[FieldSchema1]
    """Extracted data matching the requested schema"""
    metadata: StagehandResultMetadata


class FieldSchema0(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema0"]], dict[StrictStr, Optional["FieldSchema0"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema0"]], dict[StrictStr, Optional["FieldSchema0"]]]]


class FieldSchema1(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema1"]], dict[StrictStr, Optional["FieldSchema1"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema1"]], dict[StrictStr, Optional["FieldSchema1"]]]]


class FieldSchema10(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema10"]], dict[StrictStr, Optional["FieldSchema10"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema10"]], dict[StrictStr, Optional["FieldSchema10"]]]]


class FieldSchema11(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema11"]], dict[StrictStr, Optional["FieldSchema11"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema11"]], dict[StrictStr, Optional["FieldSchema11"]]]]


class FieldSchema12(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema12"]], dict[StrictStr, Optional["FieldSchema12"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema12"]], dict[StrictStr, Optional["FieldSchema12"]]]]


class FieldSchema13(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema13"]], dict[StrictStr, Optional["FieldSchema13"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema13"]], dict[StrictStr, Optional["FieldSchema13"]]]]


class FieldSchema14(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema14"]], dict[StrictStr, Optional["FieldSchema14"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema14"]], dict[StrictStr, Optional["FieldSchema14"]]]]


class FieldSchema2(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema2"]], dict[StrictStr, Optional["FieldSchema2"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema2"]], dict[StrictStr, Optional["FieldSchema2"]]]]


class FieldSchema3(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema3"]], dict[StrictStr, Optional["FieldSchema3"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema3"]], dict[StrictStr, Optional["FieldSchema3"]]]]


class FieldSchema4(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema4"]], dict[StrictStr, Optional["FieldSchema4"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema4"]], dict[StrictStr, Optional["FieldSchema4"]]]]


class FieldSchema5(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema5"]], dict[StrictStr, Optional["FieldSchema5"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema5"]], dict[StrictStr, Optional["FieldSchema5"]]]]


class FieldSchema6(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema6"]], dict[StrictStr, Optional["FieldSchema6"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema6"]], dict[StrictStr, Optional["FieldSchema6"]]]]


class FieldSchema7(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema7"]], dict[StrictStr, Optional["FieldSchema7"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema7"]], dict[StrictStr, Optional["FieldSchema7"]]]]


class FieldSchema8(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema8"]], dict[StrictStr, Optional["FieldSchema8"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema8"]], dict[StrictStr, Optional["FieldSchema8"]]]]


class FieldSchema9(
    RootModel[Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema9"]], dict[StrictStr, Optional["FieldSchema9"]]]]]
):
    root: Optional[Union[StrictStr, StrictInt, StrictFloat, StrictBool, list[Optional["FieldSchema9"]], dict[StrictStr, Optional["FieldSchema9"]]]]


class GoogleModelName(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^google\\/(gemini-2\\.0-flash|gemini-2\\.0-flash-001|gemini-2\\.0-flash-lite|gemini-2\\.0-flash-lite-001|gemini-2\\.5-pro|gemini-2\\.5-flash|gemini-2\\.5-flash-image|gemini-2\\.5-flash-lite|gemini-2\\.5-flash-preview-tts|gemini-2\\.5-pro-preview-tts|gemini-2\\.5-flash-native-audio-latest|gemini-2\\.5-flash-native-audio-preview-09-2025|gemini-2\\.5-flash-native-audio-preview-12-2025|gemini-2\\.5-computer-use-preview-10-2025|gemini-3-pro-preview|gemini-3-pro-image-preview|gemini-3-flash-preview|gemini-3\\.1-pro-preview|gemini-3\\.1-pro-preview-customtools|gemini-3\\.1-flash-image-preview|gemini-3\\.1-flash-lite-preview|gemini-3\\.1-flash-tts-preview|gemini-3\\.5-flash|gemini-3\\.6-flash|gemini-pro-latest|gemini-flash-latest|gemini-flash-lite-latest|deep-research-pro-preview-12-2025|deep-research-max-preview-04-2026|deep-research-preview-04-2026|nano-banana-pro-preview|aqa|gemini-robotics-er-1\\.5-preview|gemma-3-1b-it|gemma-3-4b-it|gemma-3n-e4b-it|gemma-3n-e2b-it|gemma-3-12b-it|gemma-3-27b-it)$"
        ),
    ]


class GroqModelName(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^groq\\/(gemma2-9b-it|llama-3\\.1-8b-instant|llama-3\\.3-70b-versatile|meta-llama\\/llama-guard-4-12b|openai\\/gpt-oss-120b|openai\\/gpt-oss-20b|deepseek-r1-distill-llama-70b|meta-llama\\/llama-4-maverick-17b-128e-instruct|meta-llama\\/llama-4-scout-17b-16e-instruct|meta-llama\\/llama-prompt-guard-2-22m|meta-llama\\/llama-prompt-guard-2-86m|moonshotai\\/kimi-k2-instruct-0905|qwen\\/qwen3-32b|llama-guard-3-8b|llama3-70b-8192|llama3-8b-8192|mixtral-8x7b-32768|qwen-qwq-32b|qwen-2\\.5-32b|deepseek-r1-distill-qwen-32b)$"
        ),
    ]


class HttpVersion(StrEnum):
    field_1 = "1"
    field_2 = "2"


class ImplementationInfo(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: Annotated[StrictStr, Field(min_length=1)]
    version: Annotated[StrictStr, Field(min_length=1)]


class InputFilePayload(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: Annotated[StrictStr, Field(min_length=1)]
    mime_type: Annotated[Optional[StrictStr], Field(min_length=1)] = None
    data: Annotated[
        StrictStr,
        Field(
            json_schema_extra={"contentEncoding": "base64"},
            max_length=69905068,
            pattern="^$|^(?:[0-9a-zA-Z+/]{4})*(?:(?:[0-9a-zA-Z+/]{2}==)|(?:[0-9a-zA-Z+/]{3}=))?$",
        ),
    ]
    last_modified: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = (
        None
    )


class Instruction(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(min_length=1)]


class JSONRPCErrorObject(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    code: Annotated[StrictInt, Field(ge=-9007199254740991, le=9007199254740991)]
    message: StrictStr
    data: Optional[FieldSchema14] = None


class JSONRPCRequestId(RootModel[StrictInt]):
    root: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]


class JSONRPCErrorResponseId(RootModel[Optional[JSONRPCRequestId]]):
    root: Optional[JSONRPCRequestId]


class LLMAnnotations(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    audience: Optional[list[LLMRole]] = None
    priority: Annotated[Optional[StrictFloat], Field(ge=0.0, le=1.0)] = None
    last_modified: Optional[StrictStr] = None


class LLMClientTool(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: StrictStr
    title: Optional[StrictStr] = None
    icons: Optional[list[LLMToolIcon]] = None
    description: Optional[StrictStr] = None
    input_schema: LLMToolJson
    execution: Optional[LLMToolExecution] = None
    output_schema: Optional[LLMToolJson] = None
    annotations: Optional[LLMToolAnnotations] = None


class LLMImageContent(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    type: Literal["image"]
    data: Annotated[
        StrictStr,
        Field(
            json_schema_extra={"contentEncoding": "base64"},
            pattern="^$|^(?:[0-9a-zA-Z+/]{4})*(?:(?:[0-9a-zA-Z+/]{2}==)|(?:[0-9a-zA-Z+/]{3}=))?$",
        ),
    ]
    mime_type: StrictStr
    annotations: Optional[LLMAnnotations] = None


class LLMJsonSchemaResponseFormat(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    type: Literal["json_schema"]
    name: StrictStr
    description: Optional[StrictStr] = None
    schema_: Annotated[Optional[FieldSchema6], Field(alias="schema")]


class LLMMessage(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    role: LLMRole
    content: Union[LLMMessageContentBlock, list[LLMMessageContentBlock]]


class LLMMessageGenerateParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    messages: list[LLMMessage]
    system_prompt: Optional[StrictStr] = None
    temperature: Optional[StrictFloat] = None
    stop_sequences: Optional[list[StrictStr]] = None
    tools: Optional[list[LLMClientTool]] = None
    tool_choice: Optional[LLMToolChoice] = None
    response_format: Optional[LLMTextResponseFormat] = None


class LLMMessageGenerateResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    role: LLMRole
    content: Union[LLMMessageContentBlock, list[LLMMessageContentBlock]]
    stop_reason: Optional[StrictStr] = None
    usage: Optional[LLMUsage] = None
    output_format: Literal["text"]


class LLMRole(StrEnum):
    user = "user"
    assistant = "assistant"


class LLMStructuredGenerateParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    messages: list[LLMMessage]
    system_prompt: Optional[StrictStr] = None
    temperature: Optional[StrictFloat] = None
    stop_sequences: Optional[list[StrictStr]] = None
    response_format: LLMJsonSchemaResponseFormat


class LLMGenerateParams(
    RootModel[Union[LLMStructuredGenerateParams, LLMMessageGenerateParams]]
):
    root: Union[LLMStructuredGenerateParams, LLMMessageGenerateParams]


class LLMStructuredGenerateResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    role: LLMRole
    content: Union[LLMMessageContentBlock, list[LLMMessageContentBlock]]
    stop_reason: Optional[StrictStr] = None
    usage: Optional[LLMUsage] = None
    output_format: Literal["json_schema"]
    structured_content: Optional[FieldSchema8]


class LLMGenerateResult(
    RootModel[Union[LLMMessageGenerateResult, LLMStructuredGenerateResult]]
):
    root: Union[LLMMessageGenerateResult, LLMStructuredGenerateResult]


class LLMTextContent(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    type: Literal["text"]
    text: StrictStr
    annotations: Optional[LLMAnnotations] = None


class LLMTextResponseFormat(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    type: Literal["text"]


class LLMToolAnnotations(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    title: Optional[StrictStr] = None
    read_only_hint: Optional[StrictBool] = None
    destructive_hint: Optional[StrictBool] = None
    idempotent_hint: Optional[StrictBool] = None
    open_world_hint: Optional[StrictBool] = None


class LLMToolChoice(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    mode: Optional[Mode] = None


class LLMToolExecution(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    task_support: Optional[TaskSupport] = None


class LLMToolIcon(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
        arbitrary_types_allowed=True,
    )
    src: WireUrl
    mime_type: Optional[StrictStr] = None
    sizes: Optional[list[StrictStr]] = None
    theme: Optional[Theme] = None


class LLMToolJson(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    field_schema: Annotated[Optional[StrictStr], Field(alias="$schema")] = None
    type: Literal["object"]
    properties: Optional[dict[StrictStr, dict[StrictStr, Optional[FieldSchema7]]]] = (
        None
    )
    required: Optional[list[StrictStr]] = None


class LLMToolResultContent(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    type: Literal["tool_result"]
    tool_use_id: StrictStr
    content: list[LLMToolResultContentBlock]
    structured_content: Optional[dict[StrictStr, Optional[FieldSchema5]]] = None
    is_error: Optional[StrictBool] = None


class LLMToolResultContentBlock(RootModel[Union[LLMTextContent, LLMImageContent]]):
    root: Union[LLMTextContent, LLMImageContent]


class LLMToolUseContent(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    type: Literal["tool_use"]
    id: StrictStr
    name: StrictStr
    input: dict[StrictStr, Optional[FieldSchema4]]


class LLMMessageContentBlock(
    RootModel[Union[LLMTextContent, LLMImageContent, LLMToolUseContent, LLMToolResultContent]]
):
    root: Union[LLMTextContent, LLMImageContent, LLMToolUseContent, LLMToolResultContent]


class LLMUsage(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    input_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    output_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    total_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    reasoning_tokens: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = (
        None
    )
    cached_input_tokens: Annotated[
        Optional[StrictInt], Field(ge=0, le=9007199254740991)
    ] = None


class LoadState(StrEnum):
    load = "load"
    domcontentloaded = "domcontentloaded"
    networkidle = "networkidle"


class Locator(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None


class LocatorCentroidResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    x: StrictFloat
    y: StrictFloat


class LocatorClickOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    button: Optional[MouseButton] = None
    click_count: Annotated[Optional[StrictInt], Field(gt=0, le=9007199254740991)] = None


class LocatorClickParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    options: Optional[LocatorClickOptions] = None


class LocatorClickResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    clicked: Literal[True]


class LocatorCountResult(RootModel[StrictInt]):
    root: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]


class LocatorDescriptor(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None


class LocatorFillParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    value: StrictStr


class LocatorFillResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    filled: Literal[True]


class LocatorHighlightOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    duration_ms: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    border_color: Optional[RgbaColor] = None
    content_color: Optional[RgbaColor] = None


class LocatorHighlightParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    options: Optional[LocatorHighlightOptions] = None


class LocatorHighlightResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    highlighted: Literal[True]


class LocatorHoverResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    hovered: Literal[True]


class LocatorInnerHtmlResult(RootModel[StrictStr]):
    root: StrictStr


class LocatorInnerTextResult(RootModel[StrictStr]):
    root: StrictStr


class LocatorInputValueResult(RootModel[StrictStr]):
    root: StrictStr


class LocatorIsCheckedResult(RootModel[StrictBool]):
    root: StrictBool


class LocatorIsVisibleResult(RootModel[StrictBool]):
    root: StrictBool


class LocatorScrollToParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    percent: Union[StrictFloat, StrictStr]


class LocatorScrollToResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    scrolled: Literal[True]


class LocatorSelectOptionParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    values: Union[StrictStr, list[StrictStr]]


class LocatorSelectOptionResult(RootModel[list[StrictStr]]):
    root: list[StrictStr]


class LocatorSendClickEventOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    bubbles: Optional[StrictBool] = None
    cancelable: Optional[StrictBool] = None
    composed: Optional[StrictBool] = None
    detail: Optional[StrictFloat] = None


class LocatorSendClickEventParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    options: Optional[LocatorSendClickEventOptions] = None


class LocatorSendClickEventResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    clicked: Literal[True]


class LocatorSetInputFilesParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    files: list[InputFilePayload]


class LocatorSetInputFilesResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    set: Literal[True]


class LocatorTextContentResult(RootModel[StrictStr]):
    root: StrictStr


class LocatorTypeOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    delay: Annotated[Optional[StrictFloat], Field(ge=0.0)] = None


class LocatorTypeParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    nth: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    text: StrictStr
    options: Optional[LocatorTypeOptions] = None


class LocatorTypeResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    typed: Literal[True]


class LogLevel(StrEnum):
    off = "off"
    error = "error"
    warn = "warn"
    info = "info"
    debug = "debug"


class Mode(StrEnum):
    auto = "auto"
    required = "required"
    none = "none"


class ModelConfig(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    api_key: Annotated[
        Optional[StrictStr], Field(examples=["sk-some-openai-api-key"], min_length=1)
    ] = None
    """
    API key for the model provider

    Example: 'sk-some-openai-api-key'
    """
    headers: Optional[dict[StrictStr, StrictStr]] = None
    """Custom headers sent with every request to the model provider"""
    model_name: Annotated[ModelName, Field(examples=["openai/gpt-5.4-mini"])]
    """Example: 'openai/gpt-5.4-mini'"""


class MouseButton(StrEnum):
    left = "left"
    right = "right"
    middle = "middle"


class NavigationFinishedError(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    message: StrictStr


class NavigationHeader(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: StrictStr
    value: StrictStr


class NavigationResponseDescriptor(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    response_id: Annotated[StrictStr, Field(min_length=1)]
    url: StrictStr
    status: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    status_text: StrictStr
    headers: dict[StrictStr, StrictStr]
    from_service_worker: StrictBool


class NavigationSecurityDetails(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    issuer: StrictStr
    protocol: StrictStr
    subject_name: StrictStr
    valid_from: StrictFloat
    valid_to: StrictFloat


class NavigationServerAddr(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    ip_address: StrictStr
    port: Annotated[StrictInt, Field(ge=0, le=65535)]


class ObserveOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    model: Optional[ModelConfig] = None
    """Complete model configuration for this call; when omitted, the initialized Stagehand model is used, or Browserbase selects one automatically when no initialized model exists"""
    variables: Annotated[
        Optional[Variables],
        Field(
            examples=[{"username": {"value": "john@example.com", "description": "The login email"}, "rememberMe": True}]
        ),
    ] = None
    """
    Variables whose names are exposed to the model so observe() returns %variableName% placeholders in suggested action arguments instead of literal values. Accepts flat primitives or { value, description? } objects.

    Example: {'username': {'value': 'john@example.com', 'description': 'The login email'}, 'rememberMe': True}
    """
    timeout: Annotated[Optional[StrictFloat], Field(examples=[30000])] = None
    """
    Timeout in ms for the observation

    Example: 30000
    """
    locator: Optional[Locator] = None
    """Locator that scopes observation to a specific element"""
    ignore_locators: Annotated[
        Optional[list[Locator]],
        Field(
            examples=[[{"selector": "nav"}, {"selector": ".cookie-banner"}, {"selector": "#sidebar-ads"}]]
        ),
    ] = None
    """
    Locators for elements and subtrees that should be excluded from observation

    Example: [{'selector': 'nav'}, {'selector': '.cookie-banner'}, {'selector': '#sidebar-ads'}]
    """
    cache: Optional[Caching] = None
    """Override the instance-level cache setting for this request"""


class ObserveResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    data: list[Action]
    metadata: StagehandResultMetadata


class OpenAIModelName(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^openai\\/(gpt-4\\.1|gpt-4\\.1-2025-04-14|gpt-4\\.1-mini|gpt-4\\.1-mini-2025-04-14|gpt-4\\.1-nano|gpt-4\\.1-nano-2025-04-14|gpt-4o|gpt-4o-2024-05-13|gpt-4o-2024-08-06|gpt-4o-2024-11-20|gpt-4o-audio-preview|gpt-4o-audio-preview-2024-12-17|gpt-4o-search-preview|gpt-4o-search-preview-2025-03-11|gpt-4o-mini-search-preview|gpt-4o-mini-search-preview-2025-03-11|gpt-4o-mini|gpt-4o-mini-2024-07-18|gpt-3\\.5-turbo-0125|gpt-3\\.5-turbo|gpt-3\\.5-turbo-1106|gpt-5-chat-latest|o1|o1-2024-12-17|o3|o3-2025-04-16|o3-mini|o3-mini-2025-01-31|o4-mini|o4-mini-2025-04-16|gpt-5|gpt-5-2025-08-07|gpt-5-codex|gpt-5-mini|gpt-5-mini-2025-08-07|gpt-5-nano|gpt-5-nano-2025-08-07|gpt-5-pro|gpt-5-pro-2025-10-06|gpt-5\\.1|gpt-5\\.1-chat-latest|gpt-5\\.1-codex-mini|gpt-5\\.1-codex|gpt-5\\.1-codex-max|gpt-5\\.2|gpt-5\\.2-chat-latest|gpt-5\\.2-pro|gpt-5\\.2-codex|gpt-5\\.3-chat-latest|gpt-5\\.3-codex|gpt-5\\.4|gpt-5\\.4-2026-03-05|gpt-5\\.4-mini|gpt-5\\.4-mini-2026-03-17|gpt-5\\.4-nano|gpt-5\\.4-nano-2026-03-17|gpt-5\\.4-pro|gpt-5\\.4-pro-2026-03-05|gpt-5\\.5|gpt-5\\.5-2026-04-23|gpt-5\\.6|gpt-5\\.6-luna|gpt-5\\.6-sol|gpt-5\\.6-terra)$"
        ),
    ]


class ModelName(
    RootModel[Union[OpenAIModelName, AnthropicModelName, GoogleModelName, GroqModelName, CerebrasModelName]]
):
    root: Union[OpenAIModelName, AnthropicModelName, GoogleModelName, GroqModelName, CerebrasModelName]
    """An explicitly supported model name with its provider prefix"""


class OperatingSystem(StrEnum):
    android = "android"
    ios = "ios"
    linux = "linux"
    macos = "macos"
    windows = "windows"


class Os(StrEnum):
    windows = "windows"
    mac = "mac"
    linux = "linux"
    mobile = "mobile"
    tablet = "tablet"


class PageAddInitScriptParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    source: StrictStr


class PageCDPEvent(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: Annotated[StrictStr, Field(min_length=1)]
    method: Literal["Runtime.consoleAPICalled"]
    params: PageCDPEventParams
    session_id: Annotated[StrictStr, Field(min_length=1)]
    target_id: Annotated[StrictStr, Field(min_length=1)]


class PageCDPEventNotification(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    subscription_id: Annotated[StrictStr, Field(min_length=1)]
    event: PageCDPEvent


class PageCDPEventParams(RootModel[dict[StrictStr, Optional[FieldSchema12]]]):
    root: dict[StrictStr, Optional[FieldSchema12]]


class PageClickOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    button: Optional[MouseButton] = None
    click_count: Annotated[Optional[StrictInt], Field(gt=0, le=9007199254740991)] = None


class PageClickParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    x: StrictFloat
    y: StrictFloat
    options: Optional[PageClickOptions] = None


class PageCloseResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    closed: Literal[True]


class PageDragAndDropOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    button: Optional[MouseButton] = None
    steps: Annotated[Optional[StrictInt], Field(gt=0, le=9007199254740991)] = None
    delay: Annotated[Optional[StrictFloat], Field(ge=0.0)] = None
    route: Optional[list[PageDragAndDropRoutePoint]] = None


class PageDragAndDropParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    from_x: StrictFloat
    from_y: StrictFloat
    to_x: StrictFloat
    to_y: StrictFloat
    options: Optional[PageDragAndDropOptions] = None


class PageDragAndDropRoutePoint(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    x: StrictFloat
    y: StrictFloat


class PageEvaluateParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    expression: StrictStr


class PageEvaluateResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    value: Optional[FieldSchema9]


class PageEventName(RootModel[Literal["console"]]):
    root: Literal["console"]


class PageGoBackParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    options: Optional[PageNavigationOptions] = None


class PageGoForwardParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    options: Optional[PageNavigationOptions] = None


class PageGotoParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    url: Annotated[StrictStr, Field(min_length=1)]
    options: Optional[PageNavigationOptions] = None


class PageHoverParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    x: StrictFloat
    y: StrictFloat


class PageIdParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr


class PageKeyPressOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    delay: Annotated[Optional[StrictFloat], Field(ge=0.0)] = None


class PageKeyPressParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    key: Annotated[StrictStr, Field(min_length=1)]
    options: Optional[PageKeyPressOptions] = None


class PageNavigationOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    wait_until: Optional[LoadState] = None
    timeout: Annotated[Optional[StrictInt], Field(gt=0, le=9007199254740991)] = None


class PageNavigationResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page: PageRef
    response: Optional[NavigationResponseDescriptor]


class PageOffParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    subscription_id: Annotated[StrictStr, Field(min_length=1)]


class PageOnParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    subscription_id: Annotated[StrictStr, Field(min_length=1)]
    event: PageEventName


class PageRef(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    url: Optional[StrictStr] = None
    title: Optional[StrictStr] = None


class ContextActivePageResult(RootModel[Optional[PageRef]]):
    root: Optional[PageRef]


class ContextPagesResult(RootModel[list[PageRef]]):
    root: list[PageRef]


class PageReloadOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    wait_until: Optional[LoadState] = None
    timeout: Annotated[Optional[StrictInt], Field(gt=0, le=9007199254740991)] = None
    ignore_cache: Optional[StrictBool] = None


class PageReloadParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    options: Optional[PageReloadOptions] = None


class PageScreenshotClip(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    x: StrictFloat
    y: StrictFloat
    width: Annotated[StrictFloat, Field(gt=0.0)]
    height: Annotated[StrictFloat, Field(gt=0.0)]


class PageScreenshotOptions(PageScreenshotOptionsValidation):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    animations: Optional[Animations] = None
    caret: Optional[Caret] = None
    clip: Optional[PageScreenshotClip] = None
    full_page: Optional[StrictBool] = None
    mask: Optional[list[LocatorDescriptor]] = None
    mask_color: Optional[StrictStr] = None
    omit_background: Optional[StrictBool] = None
    quality: Annotated[Optional[StrictInt], Field(ge=0, le=100)] = None
    scale: Optional[Scale] = None
    style: Optional[StrictStr] = None
    timeout: Annotated[Optional[StrictFloat], Field(ge=0.0)] = None
    type: Optional[Type] = None


class PageScreenshotParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    options: Optional[PageScreenshotOptions] = None


class PageScreenshotResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    data: Annotated[
        StrictStr,
        Field(
            json_schema_extra={"contentEncoding": "base64"},
            pattern="^$|^(?:[0-9a-zA-Z+/]{4})*(?:(?:[0-9a-zA-Z+/]{2}==)|(?:[0-9a-zA-Z+/]{3}=))?$",
        ),
    ]


class PageScrollParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    x: StrictFloat
    y: StrictFloat
    delta_x: StrictFloat
    delta_y: StrictFloat


class PageSetExtraHTTPHeadersParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    headers: dict[StrictStr, StrictStr]


class PageSetViewportSizeOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    device_scale_factor: Annotated[Optional[StrictFloat], Field(gt=0.0)] = None


class PageSetViewportSizeParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    width: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    height: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    options: Optional[PageSetViewportSizeOptions] = None


class PageSnapshotOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    include_iframes: Optional[StrictBool] = None


class PageSnapshotParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    options: Optional[PageSnapshotOptions] = None


class PageTitleResult(RootModel[StrictStr]):
    root: StrictStr


class PageTypeOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    delay: Annotated[Optional[StrictFloat], Field(ge=0.0)] = None
    with_mistakes: Optional[StrictBool] = None


class PageTypeParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    text: StrictStr
    options: Optional[PageTypeOptions] = None


class PageUrlResult(RootModel[StrictStr]):
    root: StrictStr


class PageVoidResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    ok: Literal[True]


class PageWaitForLoadStateParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    state: LoadState
    timeout: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None


class PageWaitForSelectorOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    state: Optional[State] = None
    timeout: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = None
    pierce_shadow: Optional[StrictBool] = None


class PageWaitForSelectorParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    selector: Annotated[StrictStr, Field(min_length=1)]
    options: Optional[PageWaitForSelectorOptions] = None


class PageWaitForSelectorResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    matched: StrictBool


class PageWaitForTimeoutParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    ms: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]


class PageWebMCPCancelInvocationParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    invocation_id: Annotated[StrictStr, Field(min_length=1)]


class PageWebMCPInvocationResultParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    invocation_id: Annotated[StrictStr, Field(min_length=1)]
    options: Optional[WebMCPResultOptions] = None


class PageWebMCPInvokeToolParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    frame_id: Annotated[StrictStr, Field(min_length=1)]
    tool_name: Annotated[StrictStr, Field(min_length=1)]
    input: Annotated[dict[StrictStr, WebMCPJsonValue], Field(validate_default=True)] = {

    }


class PageWebMCPToolsParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: StrictStr
    options: Optional[WebMCPToolsOptions] = None


class PageWebMCPToolsResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    tools: list[WebMCPToolDescriptor]


class ProxyConfig(RootModel[Union[BrowserbaseProxyConfig, ExternalProxyConfig]]):
    root: Union[BrowserbaseProxyConfig, ExternalProxyConfig]


class ResponseAllHeadersResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    headers: dict[StrictStr, StrictStr]


class ResponseBodyResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    body: StrictStr
    base64_encoded: Literal[True]


class ResponseFinishedResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    error: Optional[NavigationFinishedError]


class ResponseHeadersArrayResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    headers: list[NavigationHeader]


class ResponseIdParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    response_id: Annotated[StrictStr, Field(min_length=1)]


class ResponseSecurityDetailsResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    value: Optional[NavigationSecurityDetails]


class ResponseServerAddrResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    value: Optional[NavigationServerAddr]


class RgbaColor(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    r: StrictFloat
    g: StrictFloat
    b: StrictFloat
    a: Optional[StrictFloat] = None


class SameSite(StrEnum):
    strict = "Strict"
    lax = "Lax"
    none = "None"


class Scale(StrEnum):
    css = "css"
    device = "device"


class Shortcut(StrEnum):
    control_or_meta_v = "ControlOrMeta+V"
    meta_v = "Meta+V"
    control_v = "Control+V"


class SnapshotResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    formatted_tree: StrictStr
    xpath_map: dict[StrictStr, StrictStr]
    url_map: dict[StrictStr, StrictStr]


class StagehandActParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: Annotated[StrictStr, Field(min_length=1)]
    instruction: Union[Instruction, Action]
    options: Optional[ActOptions] = None


class StagehandCloseResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    closed: Literal[True]


class StagehandExtractParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: Annotated[StrictStr, Field(min_length=1)]
    instruction: Annotated[StrictStr, Field(min_length=1)]
    schema_: Annotated[Optional[FieldSchema0], Field(alias="schema", validate_default=True)] = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "properties": {"extraction": {"type": "string"}},
        "required": ["extraction"],
        "additionalProperties": False,
    }
    options: Optional[ExtractOptions] = None


class StagehandInitParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
        arbitrary_types_allowed=True,
    )
    protocol_version: Annotated[
        StrictStr,
        Field(
            pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[A-Za-z-][0-9A-Za-z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$"
        ),
    ]
    client_info: ImplementationInfo
    browser_cdp_url: Annotated[Optional[StrictStr], Field(min_length=1)] = None
    api_key: Annotated[Optional[StrictStr], Field(min_length=1)] = None
    api_url: Optional[WireUrl] = None
    """Stagehand API base URL override for managed services such as Model Gateway and server-side caching"""
    browser: Optional[BrowserSessionMetadata] = None
    model: Optional[Union[ModelConfig, ClientModelReference]] = None
    """Default model configuration; when omitted and a Browserbase Model Gateway session is available, Browserbase selects a model automatically for inference calls"""
    telemetry: Annotated[TelemetryConfig, Field(validate_default=True)] = {
        "traces": {"endpoint": "https://example.com/v1/traces", "headers": {}}
    }
    log_level: LogLevel = LogLevel.info
    system_prompt: Optional[StrictStr] = None
    self_heal: Optional[StrictBool] = None
    dom_settle_timeout_ms: Annotated[
        Optional[StrictInt], Field(gt=0, le=9007199254740991)
    ] = None
    cache: Optional[Caching] = None
    """Server-side caching of act/observe/extract results for this instance: a boolean toggle, or an object with an optional hit-count threshold. Requires a Browserbase apiKey and browser sessionId. Can be overridden per request via options.cache."""


class StagehandInitResult(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    initialized: Literal[True]
    pages: list[PageRef]


class StagehandLog(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    level: StagehandLogLevel
    message: Annotated[StrictStr, Field(min_length=1)]
    data: StagehandLogData


class StagehandLogData(RootModel[dict[StrictStr, Optional[FieldSchema11]]]):
    root: dict[StrictStr, Optional[FieldSchema11]]


class StagehandLogLevel(StrEnum):
    debug = "debug"
    info = "info"
    warn = "warn"
    error = "error"


class StagehandMetrics(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    act_prompt_tokens: StrictFloat
    act_completion_tokens: StrictFloat
    act_reasoning_tokens: StrictFloat
    act_cached_input_tokens: StrictFloat
    act_inference_time_ms: StrictFloat
    extract_prompt_tokens: StrictFloat
    extract_completion_tokens: StrictFloat
    extract_reasoning_tokens: StrictFloat
    extract_cached_input_tokens: StrictFloat
    extract_inference_time_ms: StrictFloat
    observe_prompt_tokens: StrictFloat
    observe_completion_tokens: StrictFloat
    observe_reasoning_tokens: StrictFloat
    observe_cached_input_tokens: StrictFloat
    observe_inference_time_ms: StrictFloat
    total_prompt_tokens: StrictFloat
    total_completion_tokens: StrictFloat
    total_reasoning_tokens: StrictFloat
    total_cached_input_tokens: StrictFloat
    total_inference_time_ms: StrictFloat


class StagehandObserveParams(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    page_id: Annotated[StrictStr, Field(min_length=1)]
    instruction: Optional[StrictStr] = None
    options: Optional[ObserveOptions] = None


class StagehandResultMetadata(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    action_id: Optional[StrictStr] = None
    """Action ID for tracking"""
    cache: CacheMetadata
    """Cache observability for this result; status is DISABLED when no cache lookup ran"""
    usage: StagehandResultUsage
    """Aggregate LLM usage for this operation; zeroed when the operation did not run inference"""


class StagehandResultUsage(WireModel):
    """Aggregate LLM usage for one Stagehand operation"""

    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    input_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)] = 0
    """Input tokens consumed by all LLM calls made for this operation"""
    output_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)] = 0
    """Output tokens consumed by all LLM calls made for this operation"""
    reasoning_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)] = 0
    """Reasoning tokens consumed by all LLM calls made for this operation"""
    cached_input_tokens: Annotated[StrictInt, Field(ge=0, le=9007199254740991)] = 0
    """Cached input tokens used by all LLM calls made for this operation"""
    inference_time_ms: Annotated[StrictInt, Field(ge=0, le=9007199254740991)] = 0
    """Total time spent waiting for LLM inference during this operation"""


class State(StrEnum):
    attached = "attached"
    detached = "detached"
    visible = "visible"
    hidden = "hidden"


class TaskSupport(StrEnum):
    forbidden = "forbidden"
    optional = "optional"
    required = "required"


class TelemetryConfig(TelemetryConfigValidation):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    traces: TelemetryTraces


class TelemetryTraces(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
        arbitrary_types_allowed=True,
    )
    endpoint: WireUrl
    headers: dict[StrictStr, StrictStr] = {}


class Theme(StrEnum):
    light = "light"
    dark = "dark"


class Type(StrEnum):
    png = "png"
    jpeg = "jpeg"


class VariablePrimitive(RootModel[Union[StrictStr, StrictFloat, StrictBool]]):
    root: Union[StrictStr, StrictFloat, StrictBool]


class VariableValue(RootModel[Union[VariablePrimitive, DescribedVariableValue]]):
    root: Union[VariablePrimitive, DescribedVariableValue]


class Variables(RootModel[dict[StrictStr, VariableValue]]):
    root: dict[StrictStr, VariableValue]


class WebMCPAnnotation(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    read_only: Optional[StrictBool] = None
    untrusted_content: Optional[StrictBool] = None
    autosubmit: Optional[StrictBool] = None


class WebMCPInvocationDescriptor(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    invocation_id: Annotated[StrictStr, Field(min_length=1)]
    tool_name: Annotated[StrictStr, Field(min_length=1)]
    frame_id: Annotated[StrictStr, Field(min_length=1)]
    input: dict[StrictStr, WebMCPJsonValue]


class WebMCPInvocationStatus(StrEnum):
    completed = "Completed"
    canceled = "Canceled"
    error = "Error"


class WebMCPJsonValue(RootModel[Optional[FieldSchema10]]):
    root: Optional[FieldSchema10]


class WebMCPRemoteObject(RootModel[dict[StrictStr, WebMCPJsonValue]]):
    root: dict[StrictStr, WebMCPJsonValue]


class WebMCPResultOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    timeout: Annotated[Optional[StrictFloat], Field(ge=0.0)] = None


class WebMCPToolDescriptor(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    name: Annotated[StrictStr, Field(min_length=1)]
    description: StrictStr
    input_schema: Optional[dict[StrictStr, WebMCPJsonValue]] = None
    annotations: Optional[WebMCPAnnotation] = None
    frame_id: Annotated[StrictStr, Field(min_length=1)]
    backend_node_id: Annotated[Optional[StrictInt], Field(ge=0, le=9007199254740991)] = (
        None
    )


class WebMCPToolResponse(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    invocation_id: Annotated[StrictStr, Field(min_length=1)]
    status: WebMCPInvocationStatus
    output: Optional[WebMCPJsonValue] = None
    error_text: Optional[StrictStr] = None
    exception: Optional[WebMCPRemoteObject] = None


class WebMCPToolsOptions(WireModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    timeout: Annotated[StrictFloat, Field(ge=0.0)] = 1000


FieldSchema0.model_rebuild()
FieldSchema1.model_rebuild()
FieldSchema10.model_rebuild()
FieldSchema11.model_rebuild()
FieldSchema12.model_rebuild()
FieldSchema13.model_rebuild()
FieldSchema14.model_rebuild()
FieldSchema2.model_rebuild()
FieldSchema3.model_rebuild()
FieldSchema4.model_rebuild()
FieldSchema5.model_rebuild()
FieldSchema6.model_rebuild()
FieldSchema7.model_rebuild()
FieldSchema8.model_rebuild()
FieldSchema9.model_rebuild()
